'''Search package for family-state refinement.

Public facade for the layered search implementation:
core search mechanics, candidate decisions, stage transitions, and IO adapters.
'''

from __future__ import annotations

from .decision import DecisionContext, DecisionEngine, FamilyDecisionState, CandidateDecisionFeatures
from .decision import SaturationAnalyzer, SaturationAssessment
from .decision import (
    DecorrelationAssessment,
    DecorrelationPolicy,
    assess_decorrelation,
    decorate_with_decorrelation_assessment,
    decorrelation_rerank_enabled,
)
from .transition import (
    ContextEvidence,
    ContextProfile,
    OrchestrationProfile,
    RoundTransitionPlan,
    resolve_round_transition_plan,
    resolve_context_profile,
    resolve_orchestration_profile,  # deprecated: use resolve_stage_transition / resolve_stage_transition_from_state
)
from .core import (
    SearchBudget,
    SearchEdge,
    SearchEngine,
    SearchFrontier,
    SearchNode,
    SearchNormalizer,
    SearchPolicy,
    build_search_normalizer,
    compute_base_score,
    compute_frontier_score,
    winner_improved,
)
from .io import (
    load_candidate_records_from_completed_runs,
    load_multi_run_candidate_records,
    load_single_run_candidate_records,
    resolve_materialized_child_run_dir,
    resolve_materialized_multi_run_dir,
    resolve_materialized_single_run_dir,
)
from .policy_config import (
    DEFAULT_POLICY_CONFIG,
    RefinePolicyConfig,
    RoundTransitionPolicyConfig,
    SearchPolicyBaseConfig,
    SearchPolicyConfig,
    SearchPolicyModeConfig,
    SearchPolicyPresetConfig,
    SearchPolicyTargetProfileConfig,
    get_default_policy_config,
    policy_config_from_mapping,
    policy_config_to_dict,
)
from .transition import SignalExtractor, StageTransitionSignals
from .transition import (
    ShadowPolicyRule,
    compare_stage_transition_decisions,
    get_stage_policy_table,
    get_shadow_stage_policy_table,
    resolve_stage_table_policy,
    resolve_shadow_table_policy,
)
from .transition import (
    EvaluationFeedback,
    FamilyState,
    PhasePolicyRule,
    RefinementAction,
    StageTransitionDecision,
    StageTransitionEvidence,
    build_stage_transition_evidence,
    build_stage_transition_shadow,
    get_phase_policy_table,
    resolve_stage_transition,
    resolve_stage_transition_from_state,
)

__all__ = [
    "SearchBudget",
    "CandidateDecisionFeatures",
    "ContextEvidence",
    "ContextProfile",
    "DEFAULT_POLICY_CONFIG",
    "DecorrelationAssessment",
    "DecorrelationPolicy",
    "OrchestrationProfile",
    "DecisionContext",
    "DecisionEngine",
    "EvaluationFeedback",
    "FamilyDecisionState",
    "FamilyState",
    "PhasePolicyRule",
    "RefinementAction",
    "RefinePolicyConfig",
    "RoundTransitionPolicyConfig",
    "RoundTransitionPlan",
    "SearchEdge",
    "SearchEngine",
    "SearchFrontier",
    "SearchNode",
    "SearchNormalizer",
    "SearchPolicy",
    "SearchPolicyBaseConfig",
    "SearchPolicyConfig",
    "SearchPolicyModeConfig",
    "SearchPolicyPresetConfig",
    "SearchPolicyTargetProfileConfig",
    "ShadowPolicyRule",
    "SignalExtractor",
    "SaturationAnalyzer",
    "SaturationAssessment",
    "StageTransitionDecision",
    "StageTransitionEvidence",
    "StageTransitionSignals",
    "assess_decorrelation",
    "build_stage_transition_evidence",
    "build_stage_transition_shadow",
    "compare_stage_transition_decisions",
    "decorate_with_decorrelation_assessment",
    "decorrelation_rerank_enabled",
    "get_phase_policy_table",
    "get_default_policy_config",
    "get_stage_policy_table",
    "get_shadow_stage_policy_table",
    "build_search_normalizer",
    "compute_base_score",
    "compute_frontier_score",
    "load_candidate_records_from_completed_runs",
    "load_multi_run_candidate_records",
    "load_single_run_candidate_records",
    "policy_config_from_mapping",
    "policy_config_to_dict",
    "resolve_materialized_child_run_dir",
    "resolve_materialized_multi_run_dir",
    "resolve_materialized_single_run_dir",
    "resolve_context_profile",
    "resolve_orchestration_profile",
    "resolve_round_transition_plan",
    "resolve_stage_table_policy",
    "resolve_shadow_table_policy",
    "resolve_stage_transition",
    "resolve_stage_transition_from_state",
    "winner_improved",
]
