from __future__ import annotations


PROMPT_OPERATOR_DESCRIPTIONS = (
    "add(x, y) / x + y",
    "sub(x, y) / x - y",
    "mul(x, y) / x * y",
    "div(x, y) / x / y",
    "gt(x, y) / x > y",
    "lt(x, y) / x < y",
    "ge(x, y) / x >= y",
    "le(x, y) / x <= y",
    "eq(x, y) / x == y",
    "ne(x, y) / x != y",
    "and(x, y) / logical and",
    "or(x, y) / logical or",
    "not(x) / logical not",
    "neg(x) / -x",
    "where(cond, x, y)",
    "if_then_else(cond, x, y)",
    "rank(x)",
    "zscore(x)",
    "cs_mean(x)",
    "cs_sum(x)",
    "cs_std(x)",
    "cs_skew(x, min_count=3)",
    "cs_rank(x)",
    "cs_zscore(x)",
    "ts_var(x, window)",
    "ts_ir(x, window)",
    "ts_skew(x, window)",
    "ts_kurt(x, window)",
    "ts_rank(x, window)",
    "corr(x, y, window)",
    "ts_corr(x, y, window)",
    "cov(x, y, window)",
    "ts_cov(x, y, window)",
    "std(x, window)",
    "ts_std(x, window)",
    "mean(x, window)",
    "ts_mean(x, window)",
    "sma(x, window, m=1)",
    "wma(x, window)",
    "product(x, window)",
    "sum(x, window)",
    "ts_sum(x, window)",
    "ts_count(x, window)",
    "ts_med(x, window)",
    "ts_mad(x, window)",
    "count(cond, window)",
    "sumif(x, window, cond)",
    "bucket_sum(x, key, window, q, side)",
    "max(x, window)",
    "ts_max(x, window)",
    "min(x, window)",
    "ts_min(x, window)",
    "delay(x, window)",
    "ref(x, window)",
    "delta(x, window)",
    "ts_pct_change(x, window)",
    "ema(x, window)",
    "decay_linear(x, window)",
    "ts_linear_decay_mean(x, window)",
    "ts_exp_weighted_mean_lagged(x, window)",
    "weighted_mean(x, window, half_life=H)",
    "volume_weighted_mean(x, weight, window)",
    "ts_turnover_ref_price(close, turnover, window)",
    "ts_sorted_mean_spread(value, sort_key, window, ratio)",
    "rolling_cs_spearman_mean(x, window, min_obs=10)",
    "cs_reg_resid(y, x, min_obs=20)",
    "cs_multi_reg_resid(y, x1, x2, ..., min_obs=20)",
    "ts_argmax(x, window)",
    "ts_argmin(x, window)",
    "ts_quantile(x, window, q)",
    "ts_max_diff(x, window)",
    "ts_min_diff(x, window)",
    "ts_min_max_diff(x, window)",
    "scale(x)",
    "abs(x)",
    "sign(x)",
    "log(x)",
    "slog1p(x)",
    "inv(x)",
    "sqrt(x)",
    "power(x, p)",
    "rowmax(x, y)",
    "rowmin(x, y)",
    "greater(x, y)",
    "less(x, y)",
    "highday(x, window)",
    "lowday(x, window)",
    "upper_shadow(high, open, close, preclose)",
    "macd(x, fast_window, slow_window)",
    "regbeta(x, window)",
    "regression_slope(y, x, window)",
    "regression_rsq(y, x, window)",
    "regression_residual(y, x, window)",
    "slope(x, window)",
    "rsquare(x, window)",
    "resi(x, window)",
    "rel_volume(N) = volume / mean(volume, N)",
    "rel_amount(N) = amount / mean(amount, N)",
    "advN shorthand when it clearly means mean(volume, N)",
    "indneutralize(x, industry/subindustry) when the parent family already relies on industry-neutral logic",
)

KNOWN_OPERATOR_TOKENS = frozenset(
    {
        "add",
        "sub",
        "mul",
        "div",
        "gt",
        "lt",
        "ge",
        "le",
        "eq",
        "ne",
        "and",
        "or",
        "not",
        "neg",
        "where",
        "if_then_else",
        "rank",
        "zscore",
        "cs_mean",
        "cs_sum",
        "cs_std",
        "cs_skew",
        "cs_rank",
        "cs_zscore",
        "ts_var",
        "ts_ir",
        "ts_skew",
        "ts_kurt",
        "ts_rank",
        "corr",
        "ts_corr",
        "cov",
        "ts_cov",
        "std",
        "ts_std",
        "mean",
        "ts_mean",
        "sma",
        "wma",
        "product",
        "sum",
        "ts_sum",
        "ts_count",
        "ts_med",
        "ts_mad",
        "count",
        "sumif",
        "bucket_sum",
        "max",
        "ts_max",
        "min",
        "ts_min",
        "delay",
        "ref",
        "delta",
        "ts_pct_change",
        "ema",
        "decay_linear",
        "ts_linear_decay_mean",
        "ts_exp_weighted_mean_lagged",
        "weighted_mean",
        "volume_weighted_mean",
        "ts_turnover_ref_price",
        "ts_sorted_mean_spread",
        "rolling_cs_spearman_mean",
        "cs_reg_resid",
        "cs_multi_reg_resid",
        "ts_argmax",
        "ts_argmin",
        "ts_quantile",
        "ts_max_diff",
        "ts_min_diff",
        "ts_min_max_diff",
        "scale",
        "abs",
        "sign",
        "log",
        "slog1p",
        "inv",
        "sqrt",
        "power",
        "rowmax",
        "rowmin",
        "greater",
        "less",
        "highday",
        "lowday",
        "upper_shadow",
        "macd",
        "regbeta",
        "regression_slope",
        "regression_rsq",
        "regression_residual",
        "slope",
        "rsquare",
        "resi",
        "rel_volume",
        "rel_amount",
        "sector",
        "turnover_rate",
        "midprice",
    }
)

KNOWN_EXTRA_TOKENS = frozenset(
    {"adv20", "industry", "subindustry", "indneutralize", "true", "false", "nan", "half_life", "min_obs"}
)

FUNCTION_STYLE_BINARY_OPERATORS = frozenset({"add", "sub", "mul", "div"})

EXPRESSION_TOKEN_ALIASES = frozenset(
    set(KNOWN_OPERATOR_TOKENS) | {"industry", "subindustry", "true", "false", "nan"}
)
